image: alpine/latest
sources:
- https://git.sr.ht/~sircmpwn/harec
- https://git.sr.ht/~sircmpwn/qbe
triggers:
  - action: email
    condition: failure
    to: ~sircmpwn/hare-dev@lists.sr.ht
tasks:
- qbe: |
    cd qbe
    make PREFIX=/usr
    sudo make install PREFIX=/usr
- prepare: |
    mkdir harec/build
    cd harec/build
    ../configure
- build: |
    cd harec/build
    make -j2
- tests: |
    cd harec/build
    make check
